name: Deployment Workflow
on: [push, workflow_dispatch]

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v3
    lint:
        needs: checkout
        runs-on: ubuntu-latest
        steps:
          - name: Lint
            run: npm lint