name: Deployment Workflow
on: [push, workflow_dispatch]

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v3
    setup-node:
        runs-on: ubuntu-latest
        steps:
          - name: Setup node js 
            uses: actions/setup-node@v4
          - name: Install dependencies
            run: npm ci