name: Deployment
on: push

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run:  actions/checkout@v3
            - name: Install dependecies
              run: npm ci

