name: Issue Workflow
on: issues

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code 
              run: actions/checkout@v3
            - name: Install dependecies
              run: npm ci
            - name: Lint 
              run: npm run lint

